#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

cd "$(git rev-parse --show-toplevel)"

BASE_URL='https://access.redhat.com/security/data/meta/v1/repository-to-cpe.json'

export COMMENT='
This file is automatically generated by hack/update-repository-to-cpe.sh. Do not update it directly.
'

curl -L "${BASE_URL}" | \
    jq '
        .data as $orig |
        [.data | to_entries[] |
         select(.key | test("__[0-9]+_DOT_") | not) |
         select(.value.repo_relative_urls | any(test("/aus/|/eus/|/extended-eus/"))) |
         .key as $key |
         (.value.repo_relative_urls[] |
          select(test("/aus/|/eus/|/extended-eus/")) |
          capture("/(?<major>[0-9]+)\\.(?<minor>[0-9]+)/") |
          {key: "\($key)__\(.major)_DOT_\(.minor)", value: {}})] |
        unique_by(.key) | from_entries as $generated |
        {data: ($orig + $generated)}
    ' | \
    yq '.data |
        [to_entries[].key] as $repos |
        $repos + load("hack/extra_rpm_repositories.yml").extras | sort | unique as $repos |
        $repos - load("hack/suppressed_rpm_repositories.yml").suppressed | sort | unique as $repos |
        {"rule_data": {"known_rpm_repositories": $repos}} |
        . head_comment=env(COMMENT)'
