#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

cd "$(git rev-parse --show-toplevel)"

BASE_URL='https://access.redhat.com/security/data/meta/v1/repository-to-cpe.json'

export COMMENT='
This file is automatically generated by hack/update-repository-to-cpe.sh. Do not update it directly.
'

curl -L "${BASE_URL}" | \
    yq '.data |
        [to_entries[].key] as $repos |
        $repos + load("hack/extra_rpm_repositories.yml").extras | sort | unique as $repos |
        {"rule_data": {"known_rpm_repositories": $repos}} |
        . head_comment=env(COMMENT)' > data/known_rpm_repositories.yml
