name: Push data bundle

on:
  push:
    branches:
      - main
    paths:
      - "data/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  push-data-bundle:
    runs-on: ubuntu-latest
    container:
      image: quay.io/conforma/cli:latest
    env:
      DATA_BUNDLE_REPO: quay.io/conforma/policy-data
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install oras
        run: |-
          ORAS_VERSION="1.2.2"
          curl -sL "https://github.com/oras-project/oras/releases/download/v${ORAS_VERSION}/oras_${ORAS_VERSION}_linux_amd64.tar.gz" | tar xz -C /usr/local/bin oras
          oras version

      - name: Build OPA bundle and extract merged data.json
        run: |
          ec opa build data/ -o bundle.tar.gz
          tar xzf bundle.tar.gz -C .

      - name: Login to Quay
        run: oras login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io

      - name: Push data bundle
        run: |
          DATA_BUNDLE_TAG=$(date '+%s')
          oras push "${DATA_BUNDLE_REPO}:${DATA_BUNDLE_TAG}" data.json:application/vnd.cncf.openpolicyagent.data.layer.v1+json
          oras push "${DATA_BUNDLE_REPO}:latest" data.json:application/vnd.cncf.openpolicyagent.data.layer.v1+json
